apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: smartbids-client-deployment
spec:
  selector:
    matchLabels:
      app: smartbids-client
  replicas: 2
  template:
    metadata:
      labels:
        app: smartbids-client
    spec:
      containers:
      - name: smartbids-client
        image: lmsamarawickrama/smartbids-client
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: smartbids-client-service
spec:
  selector:
    app: smartbids-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
